# Generated by Django 6.0 on 2025-12-08 07:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message='Le numéro est invalide, veuillez entrer un numéro valide', regex='^(\\+226|\\+225)?(0|5|6|7)\\d{7}$')], verbose_name='Numero WhatsApp')),
                ('tiktok_username', models.CharField(max_length=60, unique=True, validators=[django.core.validators.RegexValidator(message="Nom d'utilisateur non-valide. Il faut commencer par '@' et votre nom d'utilisateur après!", regex='^@[\\w.]{1,23}\\w$')], verbose_name='Compte tiktok')),
            ],
        ),
    ]
