# Generated by Django 6.0 on 2025-12-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boosting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='tiktok_username',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Compte tiktok'),
        ),
    ]
