# Generated by Django 6.0 on 2025-12-08 19:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boosting', '0002_alter_inscription_tiktok_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='numero',
            field=models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='Le numéro est invalide, veuillez entrer un numéro valide', regex='^(\\+226|\\+225)?(0|5|6|7)\\d{7}$')], verbose_name='Numero WhatsApp'),
        ),
    ]
